theme: jekyll-theme-minimal
title: Daniel Hills
description: ...
logo: logo.png

social_links: true
email: "mailto:danieljahills@gmail.com"
github: "https://github.com/danielhills"
linkedin: "https://www.linkedin.com/in/danieljahills/"
